Repository Umc8th-Snack/Back-end, pull requests merged in 2025-08, with the labels that each got.

#121 feat (memo) : 메모 목록 조회 구현
  src/main/java/umc/snack/controller/memo/MemoController.java
  src/main/java/umc/snack/converter/memo/MemoConverter.java
  src/main/java/umc/snack/domain/memo/dto/MemoResponseDto.java
  src/main/java/umc/snack/domain/memo/entity/Memo.java
  src/main/java/umc/snack/repository/memo/MemoRepository.java
  src/main/java/umc/snack/service/memo/MemoQueryService.java
  src/main/java/umc/snack/service/memo/MemoQueryServiceImpl.java
Labels: feat

#122 Refactor/nlp server
  docker-compose.yml
  infra/nginx/conf.d/default.conf
  python-nlp-service/Dockerfile
  python-nlp-service/bootstrap.py
  python-nlp-service/nlp_processor.py
  python-nlp-service/requirements.txt
  python-nlp-service/scripts/train_tfidf_model.py
Labels: feat

#124 [1팀] 스웨거 세팅 및 API Response
  src/main/java/umc/snack/common/config/SecurityConfig.java
  src/main/java/umc/snack/common/config/security/jwt/JWTFilter.java
  src/main/java/umc/snack/common/config/security/jwt/LoginFilter.java
  src/main/java/umc/snack/controller/auth/AuthController.java
  src/main/java/umc/snack/controller/user/UserController.java
  src/main/java/umc/snack/service/auth/LogoutService.java
  src/main/java/umc/snack/service/auth/ReissueService.java
Labels: refactor

#130 [fix] 개선된 퀴즈 채점 API: 에러 처리 및 JSON 구조 변경
  src/main/java/umc/snack/controller/quiz/QuizController.java
  src/main/java/umc/snack/service/quiz/QuizService.java
Labels: fix

#136 fix(feed) : 메인 피드 카테고리 선택 개수 수정
  src/main/java/umc/snack/controller/feed/FeedController.java
  src/main/java/umc/snack/controller/memo/MemoController.java
  src/main/java/umc/snack/repository/feed/FeedRepository.java
  src/main/java/umc/snack/service/feed/FeedService.java
  src/main/java/umc/snack/service/feed/FeedServiceImpl.java
Labels: fix

#134 [feat] 회원탈퇴 API 구현
  src/main/java/umc/snack/common/config/SecurityConfig.java
  src/main/java/umc/snack/common/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/umc/snack/controller/user/UserController.java
  src/main/java/umc/snack/domain/user/entity/User.java
  src/main/java/umc/snack/repository/auth/RefreshTokenRepository.java
  src/main/java/umc/snack/repository/memo/MemoRepository.java
  src/main/java/umc/snack/repository/scrap/UserScrapRepository.java
  src/main/java/umc/snack/service/user/UserService.java
Labels: feat

#138 [feat] 사용자 정보 조회 API 구현
  src/main/java/umc/snack/controller/user/UserController.java
  src/main/java/umc/snack/domain/user/dto/UserInfoResponseDto.java
  src/main/java/umc/snack/service/user/UserService.java
Labels: feat

#143 [리팩토링] 퀴즈 업데이트 오류 처리: JSON 파싱 문제에 대한 구체적인 오류 코드 추가
  src/main/java/umc/snack/common/exception/ErrorCode.java
  src/main/java/umc/snack/controller/memo/MemoRedirectController.java
  src/main/java/umc/snack/controller/quiz/QuizController.java
  src/main/java/umc/snack/service/quiz/QuizService.java
Labels: refactor

#145 [Feat] 사용자 정보 수정 기능 구현: 닉네임, 프로필 이미지, 소개 업데이트 API 추가
  src/main/java/umc/snack/controller/user/UserController.java
  src/main/java/umc/snack/domain/user/dto/UserUpdateRequestDto.java
  src/main/java/umc/snack/domain/user/dto/UserUpdateResponseDto.java
  src/main/java/umc/snack/domain/user/entity/User.java
  src/main/java/umc/snack/service/user/UserService.java
Labels: feat

#154 feat(memo) : 메모 조회 구현
  src/main/java/umc/snack/controller/memo/MemoController.java
  src/main/java/umc/snack/domain/memo/dto/MemoResponseDto.java
  src/main/java/umc/snack/repository/memo/MemoRepository.java
  src/main/java/umc/snack/service/memo/MemoCommandServiceImpl.java
  src/main/java/umc/snack/service/memo/MemoQueryService.java
  src/main/java/umc/snack/service/memo/MemoQueryServiceImpl.java
Labels: feat

#157 [hotfix] 스케줄링 로직 수정
  src/main/java/umc/snack/crawler/scheduler/ArticleScheduler.java
  src/main/java/umc/snack/global/gemini/GeminiResponseDto.java
  src/main/java/umc/snack/repository/article/ArticleRepository.java
  src/main/java/umc/snack/service/article/ArticleSummarizeService.java
Labels: fix

#159 [fix] 프로필 이미지 처리 업데이트
  src/main/java/umc/snack/domain/user/dto/UserInfoResponseDto.java
  src/main/java/umc/snack/domain/user/dto/UserUpdateRequestDto.java
  src/main/java/umc/snack/domain/user/dto/UserUpdateResponseDto.java
  src/main/java/umc/snack/domain/user/entity/User.java
  src/main/java/umc/snack/service/file/S3FileService.java
  src/main/java/umc/snack/service/user/UserService.java
Labels: fix

#162 [fix] ErrorCode 수정
  src/main/java/umc/snack/common/config/SecurityConfig.java
  src/main/java/umc/snack/common/config/properties/JwtProperties.java
  src/main/java/umc/snack/common/config/security/jwt/JWTFilter.java
  src/main/java/umc/snack/common/config/security/jwt/JWTUtil.java
  src/main/java/umc/snack/common/config/security/jwt/LoginFilter.java
  src/main/java/umc/snack/common/exception/ErrorCode.java
  src/main/java/umc/snack/service/auth/GoogleOAuthService.java
  src/main/java/umc/snack/service/auth/LogoutService.java
  src/main/java/umc/snack/service/auth/ReissueService.java
  src/main/resources/application.yml
Labels: chore

#164 [refactor] response 형식 통일
  src/main/java/umc/snack/common/response/ApiResponse.java
  src/main/java/umc/snack/controller/article/ArticleController.java
  src/main/java/umc/snack/crawler/scheduler/ArticleScheduler.java
  src/main/java/umc/snack/crawler/service/ArticleCollectorService.java
Labels: refactor

#166 [hotfix] Build시 LoginType 설정
  src/main/java/umc/snack/crawler/scheduler/ArticleScheduler.java
  src/main/java/umc/snack/domain/user/entity/User.java
  src/main/java/umc/snack/repository/article/CrawledArticleRepository.java
  src/main/java/umc/snack/service/article/ArticleSummarizeService.java
  src/main/java/umc/snack/service/auth/GoogleOAuthService.java
  src/main/java/umc/snack/service/user/UserService.java
Labels: fix

#170 [fix] 메모 목록 조회 response 수정
  src/main/java/umc/snack/common/exception/ErrorCode.java
  src/main/java/umc/snack/controller/feed/FeedController.java
  src/main/java/umc/snack/controller/memo/MemoController.java
  src/main/java/umc/snack/controller/memo/MyMemoController.java
  src/main/java/umc/snack/converter/memo/MemoConverter.java
  src/main/java/umc/snack/domain/memo/dto/MemoResponseDto.java
  src/main/java/umc/snack/repository/feed/FeedRepository.java
  src/main/java/umc/snack/service/feed/FeedService.java
  src/main/java/umc/snack/service/feed/FeedServiceImpl.java
Labels: fix

#169 [feat] 이메일 변경 API 구현
  src/main/java/umc/snack/common/exception/ErrorCode.java
  src/main/java/umc/snack/controller/auth/AuthController.java
  src/main/java/umc/snack/controller/user/UserController.java
  src/main/java/umc/snack/domain/user/dto/EmailChangeRequestDto.java
  src/main/java/umc/snack/domain/user/dto/EmailChangeResponseDto.java
  src/main/java/umc/snack/domain/user/entity/User.java
  src/main/java/umc/snack/service/article/ArticleSummarizeService.java
  src/main/java/umc/snack/service/user/UserService.java
Labels: feat

#174 [feat] 관련 기사 조회 기능 구현 + 카페인 캐시
  build.gradle
  src/main/java/umc/snack/SnackApplication.java
  src/main/java/umc/snack/common/config/SecurityConfig.java
  src/main/java/umc/snack/controller/article/ArticleController.java
  src/main/java/umc/snack/domain/article/dto/RelatedArticleDto.java
  src/main/java/umc/snack/repository/article/ArticleRepository.java
  src/main/java/umc/snack/service/article/ArticleService.java
  src/main/resources/application.yml
Labels: feat

#176 [feat] 키워드 기반 검색 기능 구현
  python-nlp-service/__pycache__/main.cpython-310.pyc
  python-nlp-service/__pycache__/nlp_processor.cpython-310.pyc
  python-nlp-service/bootstrap.py
  python-nlp-service/data/tfidf_vectorizer.pkl
  python-nlp-service/main.py
  python-nlp-service/nlp_processor.py
  python-nlp-service/scripts/__pycache__/__init__.cpython-310.pyc
  python-nlp-service/scripts/__pycache__/insert_stopwords_to_db.cpython-310.pyc
  python-nlp-service/scripts/__pycache__/tokenizer_utils.cpython-310.pyc
  python-nlp-service/scripts/__pycache__/train_tfidf_model.cpython-310.pyc
  python-nlp-service/scripts/train_tfidf_model.py
  src/main/java/umc/snack/common/config/RestTemplateConfig.java
  src/main/java/umc/snack/common/config/SecurityConfig.java
  src/main/java/umc/snack/common/exception/ErrorCode.java
  src/main/java/umc/snack/controller/article/ArticleController.java
  src/main/java/umc/snack/controller/feed/FeedController.java
  src/main/java/umc/snack/controller/nlp/NlpController.java
  src/main/java/umc/snack/domain/article/entity/ArticleSemanticVector.java
  src/main/java/umc/snack/domain/nlp/dto/ArticleKeywordDto.java
  src/main/java/umc/snack/domain/nlp/dto/ArticleSearchResultDto.java
  src/main/java/umc/snack/domain/nlp/dto/ArticleSimilarityResultDto.java
  src/main/java/umc/snack/domain/nlp/dto/ArticleVectorizeListRequestDto.java
  src/main/java/umc/snack/domain/nlp/dto/ArticleVectorizeListResponseDto.java
  src/main/java/umc/snack/domain/nlp/dto/ArticleVectorizeRequestDto.java
  src/main/java/umc/snack/domain/nlp/dto/ArticleVectorizeResponseDto.java
  src/main/java/umc/snack/domain/nlp/dto/FeedResponseDto.java
  src/main/java/umc/snack/domain/nlp/dto/KeywordScoreDto.java
  src/main/java/umc/snack/domain/nlp/dto/QueryVectorizeRequestDto.java
  src/main/java/umc/snack/domain/nlp/dto/QueryVectorizeResponseDto.java
  src/main/java/umc/snack/domain/nlp/dto/RecommendedArticleDto.java
  src/main/java/umc/snack/domain/nlp/dto/SearchResponseDto.java
  src/main/java/umc/snack/domain/nlp/dto/UserInteractionDto.java
  src/main/java/umc/snack/domain/nlp/dto/UserProfileRequestDto.java
  src/main/java/umc/snack/repository/feed/FeedRepository.java
  src/main/java/umc/snack/repository/nlp/ArticleSemanticVectorRepository.java
  src/main/java/umc/snack/service/feed/FeedService.java
  src/main/java/umc/snack/service/feed/FeedServiceImpl.java
  src/main/java/umc/snack/service/nlp/NlpService.java
  src/main/resources/application.yml
Labels: feat

#184 [fix] article 예외처리 추가
  src/main/java/umc/snack/service/article/ArticleService.java
Labels: fix

#186 [fix] 신고 조회 여부 api 추가
  src/main/java/umc/snack/controller/report/ReportController.java
  src/main/java/umc/snack/domain/report/dto/QuizReportResponseDto.java
  src/main/java/umc/snack/domain/report/dto/TermReportResponseDto.java
  src/main/java/umc/snack/domain/report/entity/QuizReport.java
  src/main/java/umc/snack/domain/report/entity/TermReport.java
  src/main/java/umc/snack/repository/report/QuizReportRepository.java
  src/main/java/umc/snack/repository/report/TermReportRepository.java
  src/main/java/umc/snack/service/report/QuizReportService.java
  src/main/java/umc/snack/service/report/QuizReportServiceImpl.java
  src/main/java/umc/snack/service/report/TermReportService.java
  src/main/java/umc/snack/service/report/TermReportServiceImpl.java
Labels: fix, feat

#189 [feat] 검색어 저장 및 히스토리 기능 구현 초안
  src/main/java/umc/snack/common/exception/ErrorCode.java
  src/main/java/umc/snack/controller/feed/FeedController.java
  src/main/java/umc/snack/controller/user/SearchKeywordController.java
  src/main/java/umc/snack/domain/user/SearchKeywordId.java
  src/main/java/umc/snack/domain/user/entity/SearchKeyword.java
  src/main/java/umc/snack/global/BaseEntity.java
  src/main/java/umc/snack/repository/user/SearchKeywordRepository.java
  src/main/java/umc/snack/service/user/SearchKeywordService.java
Labels: feat

#206 [feat] 비밀번호 찾기 관련 API 구현
  build.gradle
  src/main/java/umc/snack/common/config/SecurityConfig.java
  src/main/java/umc/snack/common/exception/ErrorCode.java
  src/main/java/umc/snack/controller/user/UserController.java
  src/main/java/umc/snack/crawler/scheduler/ArticleScheduler.java
  src/main/java/umc/snack/domain/user/dto/EmailRequestDto.java
  src/main/java/umc/snack/domain/user/dto/PasswordResetDto.java
  src/main/java/umc/snack/domain/user/dto/VerificationCodeDto.java
  src/main/java/umc/snack/domain/user/entity/VerificationCode.java
  src/main/java/umc/snack/repository/quiz/ArticleQuizRepository.java
  src/main/java/umc/snack/repository/user/VerificationCodeRepository.java
  src/main/java/umc/snack/service/article/ArticleSummarizeService.java
  src/main/java/umc/snack/service/nlp/NlpService.java
  src/main/java/umc/snack/service/user/UserService.java
  src/main/java/umc/snack/service/user/VerificationCodeService.java
  src/main/resources/application.yml
Labels: feat
