Repository Umc8th-Snack/Back-end, pull requests merged in 2025-07, with the labels that each got.

#41 [feat]ErrorCode 추가 (정의 및 범위 정리)
  src/main/java/umc/snack/common/exception/ErrorCode.java
Labels: feat

#43 [feat] 기사 크롤링
  build.gradle
  src/main/java/umc/snack/SnackApplication.java
  src/main/java/umc/snack/controller/article/ArticleController.java
  src/main/java/umc/snack/crawler/scheduler/ArticleScheduler.java
  src/main/java/umc/snack/crawler/service/ArticleCollectorService.java
  src/main/java/umc/snack/crawler/service/ArticleCrawlerService.java
  src/main/java/umc/snack/domain/article/entity/CrawledArticle.java
  src/main/java/umc/snack/domain/feed/entity/CategoryType.java
  src/main/java/umc/snack/init/CategoryInitializer.java
  src/main/java/umc/snack/repository/article/ArticleCategoryRepository.java
  src/main/java/umc/snack/repository/article/ArticleRepository.java
  src/main/java/umc/snack/repository/article/CrawledArticleRepository.java
  src/main/java/umc/snack/repository/feed/CategoryRepository.java
  src/main/java/umc/snack/service/article/ArticleCategoryService.java
  src/main/java/umc/snack/service/feed/CategoryService.java
  src/main/resources/application.yml
Labels: feat

#47 [fix] 크롤링 중복 필터 추가
  src/main/java/umc/snack/crawler/service/ArticleCollectorService.java
  src/main/java/umc/snack/repository/article/CrawledArticleRepository.java
  src/main/resources/application.yml
Labels: fix

#53 [feat] 메모 생성 구현
  src/main/java/umc/snack/controller/memo/MemoController.java
  src/main/java/umc/snack/converter/memo/MemoConverter.java
  src/main/java/umc/snack/domain/memo/dto/MemoRequestDto.java
  src/main/java/umc/snack/domain/memo/dto/MemoResponseDto.java
  src/main/java/umc/snack/domain/memo/dto/NoteDto.java
  src/main/java/umc/snack/domain/memo/entity/Memo.java
  src/main/java/umc/snack/repository/memo/MemoRepository.java
  src/main/java/umc/snack/service/memo/MemoCommandService.java
  src/main/java/umc/snack/service/memo/MemoCommandServiceImpl.java
  src/main/resources/application.yml
Labels: feat

#52 [feat] 퀴즈 조회
  src/main/java/umc/snack/controller/quiz/QuizController.java
  src/main/java/umc/snack/domain/quiz/dto/QuizResponseDto.java
  src/main/java/umc/snack/repository/quiz/ArticleQuizRepository.java
  src/main/java/umc/snack/repository/quiz/QuizRepository.java
  src/main/java/umc/snack/service/quiz/QuizService.java
  src/test/java/umc/snack/controller/quiz/QuizControllerSimpleTest.java
  src/test/java/umc/snack/service/quiz/QuizServiceTest.java
Labels: feat

#66 [hotfix] ArticleQuizRepository 중복 파일 제거
  src/main/java/umc/snack/global/gemini/GeminiParsingService.java
  src/main/java/umc/snack/repository/article/ArticleQuizRepository.java
Labels: fix

#60 [feat] 로그인 API (AccessToken 이용) 구현
  build.gradle
  src/main/java/umc/snack/common/config/SecurityConfig.java
  src/main/java/umc/snack/common/config/security/CustomUserDetails.java
  src/main/java/umc/snack/common/config/security/jwt/JWTFilter.java
  src/main/java/umc/snack/common/config/security/jwt/JWTUtil.java
  src/main/java/umc/snack/common/config/security/jwt/JwtTokenProvider.java
  src/main/java/umc/snack/common/config/security/jwt/LoginFilter.java
  src/main/java/umc/snack/controller/auth/AuthController.java
  src/main/java/umc/snack/domain/auth/dto/LoginRequestDto.java
  src/main/java/umc/snack/repository/user/UserRepository.java
  src/main/java/umc/snack/service/auth/CustomUserDetailsService.java
  src/main/resources/application.yml
  src/test/java/umc/snack/controller/auth/AuthControllerTest.java
Labels: feat

#75 [기능] 퀴즈 채점 API 구현
  src/main/java/umc/snack/controller/quiz/QuizController.java
  src/main/java/umc/snack/converter/memo/MemoConverter.java
  src/main/java/umc/snack/domain/quiz/dto/QuizGradingApiResponse.java
  src/main/java/umc/snack/domain/quiz/dto/QuizGradingRequestDto.java
  src/main/java/umc/snack/domain/quiz/dto/QuizGradingResponseDto.java
  src/main/java/umc/snack/repository/quiz/QuizRepository.java
  src/main/java/umc/snack/service/quiz/QuizService.java
  src/test/java/umc/snack/controller/quiz/QuizGradingControllerTest.java
  src/test/java/umc/snack/service/quiz/QuizGradingServiceTest.java
Labels: feat

#74 [1팀] 회원가입 유효성 검증 기능 추가
  src/main/java/umc/snack/common/exception/ErrorCode.java
  src/main/java/umc/snack/controller/user/UserController.java
  src/main/java/umc/snack/domain/user/dto/UserSignupRequestDto.java
  src/main/java/umc/snack/domain/user/entity/User.java
  src/main/java/umc/snack/service/user/UserService.java
  src/test/java/umc/snack/controller/user/UserControllerTest.java
Labels: feat

#89 [hotfix] AuthControllerReissueTest 테스트 메시지 수정
  src/test/java/umc/snack/controller/auth/AuthControllerReissueTest.java
Labels: fix

#80 [fix] 크롤링 마무리 및 기사 용어 조회 API 구현
  src/main/java/umc/snack/common/exception/ErrorCode.java
  src/main/java/umc/snack/controller/article/ArticleController.java
  src/main/java/umc/snack/crawler/scheduler/ArticleScheduler.java
  src/main/java/umc/snack/crawler/service/ArticleCollectorService.java
  src/main/java/umc/snack/repository/article/ArticleTermRepository.java
  src/main/java/umc/snack/service/article/ArticleService.java
  src/test/java/umc/snack/gemini/ArticleSummarizeTest.java
Labels: fix, feat

#83 [Feat] python NLP 서버 레포리토지 subtree 구조로 추가
  python-nlp-service/.gitignore
  python-nlp-service/bootstrap.py
  python-nlp-service/config.py
  python-nlp-service/data_source/stopwords.csv
  python-nlp-service/main.py
  python-nlp-service/nlp_processor.py
  python-nlp-service/requirements.txt
  python-nlp-service/scripts/__init__.py
  python-nlp-service/scripts/insert_stopwords_to_db.py
  python-nlp-service/scripts/tokenizer_utils.py
  python-nlp-service/scripts/train_tfidf_model.py
Labels: feat

#96 [Fix] share auth injection
  src/main/java/umc/snack/common/config/SecurityConfig.java
  src/main/java/umc/snack/controller/share/ShareController.java
Labels: fix

#63 fix(memo) : 메모 중복 작성 방지 예외처리
  src/main/java/umc/snack/common/exception/ErrorCode.java
  src/main/java/umc/snack/service/memo/MemoCommandServiceImpl.java
Labels: fix

#91 [Fix] quiz parsing structure 변경
  src/main/java/umc/snack/service/quiz/QuizService.java
  src/test/java/umc/snack/service/quiz/QuizServiceTest.java
Labels: fix

#95 [fix] Gemini API 프롬프트 및 스케쥴링
  src/main/java/umc/snack/common/config/SchedulerConfig.java
  src/main/java/umc/snack/crawler/scheduler/ArticleScheduler.java
  src/main/java/umc/snack/domain/article/entity/CrawledArticle.java
  src/main/java/umc/snack/global/gemini/GeminiParsingService.java
  src/main/java/umc/snack/global/gemini/GeminiResultDto.java
  src/main/java/umc/snack/repository/article/CrawledArticleRepository.java
  src/main/java/umc/snack/service/article/ArticleSummarizeService.java
  src/test/java/umc/snack/gemini/ArticleSummarizeTest.java
Labels: feat

#104 feat (feed) : 사용자 행동 로그 기반 카테고리 선호 점수 계산
  src/main/java/umc/snack/converter/feed/UserPreferenceConverter.java
  src/main/java/umc/snack/repository/feed/UserClickRepository.java
  src/main/java/umc/snack/repository/scrap/UserScrapRepository.java
  src/main/java/umc/snack/service/feed/UserPreferenceService.java
  src/test/java/umc/snack/service/feed/UserPreferenceServiceTest.java
Labels: feat

#99 [feat] 메인 피드 - 카테고리별 무한스크롤로 조회
  python-nlp-service/__pycache__/config.cpython-310.pyc
  python-nlp-service/__pycache__/config.cpython-311.pyc
  python-nlp-service/__pycache__/main.cpython-310.pyc
  python-nlp-service/__pycache__/main.cpython-311.pyc
  python-nlp-service/__pycache__/nlp_processor.cpython-310.pyc
  python-nlp-service/__pycache__/nlp_processor.cpython-311.pyc
  python-nlp-service/data/tfidf_vectorizer.pkl
  python-nlp-service/scripts/__pycache__/__init__.cpython-310.pyc
  python-nlp-service/scripts/__pycache__/insert_stopwords_to_db.cpython-310.pyc
  python-nlp-service/scripts/__pycache__/tokenizer_utils.cpython-310.pyc
  python-nlp-service/scripts/__pycache__/train_tfidf_model.cpython-310.pyc
  src/main/java/umc/snack/common/config/SecurityConfig.java
  src/main/java/umc/snack/controller/feed/FeedController.java
  src/main/java/umc/snack/converter/feed/FeedConverter.java
  src/main/java/umc/snack/domain/feed/dto/ArticleInFeedDto.java
  src/main/java/umc/snack/domain/feed/dto/IndividualArticleDto.java
  src/main/java/umc/snack/repository/feed/FeedRepository.java
  src/main/java/umc/snack/service/feed/FeedService.java
  src/main/java/umc/snack/service/feed/FeedServiceImpl.java
Labels: feat

#107 feat (feed) : 메인피드 무한스크롤 테스트 코드 추가
  src/main/java/umc/snack/SnackApplication.java
  src/main/java/umc/snack/common/config/JpaConfig.java
  src/main/java/umc/snack/controller/feed/FeedController.java
  src/main/java/umc/snack/converter/feed/UserPreferenceConverter.java
  src/test/java/umc/snack/controller/feed/FeedControllerTest.java
  src/test/java/umc/snack/controller/memo/MemoRedirectControllerTest.java
Labels: fix, feat

#113 [feat] CORS 설정 추가
  src/main/java/umc/snack/common/config/SecurityConfig.java
Labels: chore

#116 [chore] Webconfig 설정
  src/main/java/umc/snack/common/config/security/WebConfig.java
Labels: chore
